name: Composite action to checkout and cache code
description: This is a composite action that will checkout code and cache it 
inputs:
  caching:
    description: 'Input to know if caching is to be used or not '
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash